#!/bin/bash

source ~/.personal_aliases
alias ref=". ~/.bashrc"

# For work
#------------------------------------------------------------------------------
alias br="brazil"
alias bws="brazil ws"
alias bb="brazil-build"
alias bbr="brazil-build release"

# Shortcuts
#------------------------------------------------------------------------------
alias py="python3"
alias py2="python"
alias l="ls"
alias la="ls -a"
alias lal="ls -al"
alias ltr="ls -ltr"
# alias lsd="ls -d"
alias lsd="ls -d */"
alias sra="source activate tguoenv"
alias version="cat /etc/*-release"

# Movement
#------------------------------------------------------------------------------
alias k="cd .."
alias kk="cd ../.."
alias d="cd"
alias c="cd"
alias q="quirk"

# Git aliases.
#------------------------------------------------------------------------------
alias gac="git add .; git commit -m"
alias gclone="git clone"
alias gls="git ls-files"
alias gsh="git show"
alias gr="git pull --rebase"
alias gpatch="git format-patch -n HEAD^"
alias uncommit="git reset --soft HEAD^"
alias dumbcommit="git add -u ./*; git commit -m tmp"
alias lastcommit="git rev-parse HEAD"
alias lc="git rev-parse HEAD"
alias gdiff="git diff --staged"
alias unmerged="git diff --name-only --diff-filter=U"
alias unadd="git diff --name-only"
alias tocom="git diff --staged --name-only"
alias gs="git status"
alias gd="git diff"
alias gp="git push"
alias gon="git rebase --continue"
alias gau="git add -u"
alias ga="git add"
alias xga="xargs git add"
alias xag="xargs git add"
alias gc="LC_ALL=''; git commit"
alias gh="git checkout"
alias gb="git branch"
alias gl="git log --pretty=fuller"
alias gcp="git cherry-pick"
alias gap="git apply"
alias gs.="git status ."

alias gcm="git commit -m"

# git grep aliases, as historical reference.
alias gren="LC_ALL=C; git grep --color -n"
alias gw="gren -w"
alias fren="gren -F30"
alias fw="fren -w"

# tmux aliases
#------------------------------------------------------------------------------
alias tl="tmux ls"
alias tkill="tmux kill-server" # to close all tmux open sessions and server cleanly and gracefully
alias tkilla="tmux kill-session -a" # within a tmux session, to close all other sessions
alias tk="tmux kill-session -t" # followed by a session name in order to kill that one


# ls aliases.
#alias ls="ls --color" 
# The below I need for ... macCC
alias ls="ls -G" 

# Vim aliases.
alias v="vim"

# Cygwin 
alias open="cygstart.exe"

# Setup
alias vundleinstall="git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"

# file shortcuts... consider creating this function within quirk/myc
alias hist="vim ~/.bash_history"
alias ali="vim ~/dotfiles/aliases"
