#!/bin/bash

# temp
alias inst="q neo; py setup.py install; cd -"

# Shortcuts
#------------------------------------------------------------------------------
alias py="python3"
alias py2="python"
alias l="ls"
alias la="ls -al"
alias d="cd"
alias c="cd"
alias lsd="ls -d"
alias sra="source activate tguoenv"
alias q="myc"
# alias m="myc"

# NeoPulse
#------------------------------------------------------------------------------
alias neo="neopulse"
alias nl="neo list"
alias nv="neo visualize"
alias nt="neo train -p"
alias into="ssh -i tina-test.pem"

alias ref=". ~/.bashrc"

# Git aliases.
#------------------------------------------------------------------------------
alias gac="git add .; git commit -m"
alias gclone="git clone"
alias gls="git ls-files"
alias gsh="git show"
alias gr="git pull --rebase"
alias gpatch="git format-patch -n HEAD^"
alias uncommit="git reset --soft HEAD^"
alias dumbcommit="git add -u ./*; git commit -m tmp"
alias lastcommit="git rev-parse HEAD"
alias lc="git rev-parse HEAD"
alias gdiff="git diff --staged"
alias unmerged="git diff --name-only --diff-filter=U"
alias unadd="git diff --name-only"
alias tocom="git diff --staged --name-only"
alias gs="git status"
alias gd="git diff"
alias gp="git push"
alias gon="git rebase --continue"
alias gau="git add -u"
alias ga="git add"
alias xga="xargs git add"
alias xag="xargs git add"
alias gc="LC_ALL=''; git commit"
alias gh="git checkout"
alias gb="git branch"
alias gl="git log --pretty=fuller"
alias gcp="git cherry-pick"
alias gap="git apply"
alias gs.="git status ."

alias gcm="git commit -m"

# git grep aliases, as historical reference.
alias gren="LC_ALL=C; git grep --color -n"
alias gw="gren -w"
alias fren="gren -F30"
alias fw="fren -w"

# ls aliases.
alias ls="ls --color" 
# Vim aliases.
alias v="vim"

# Cygwin 
alias open="cygstart.exe"

# Setup
alias vundleinstall="git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim"


