#!/bin/bash
te=~/dotfiles/temp/other

random() {
    #klocal wef='wefwefsdfsdfsdf'
    echo hello
    # sed -i "/^cur ## /d" $te
    # echo $@
}

other() {
    local thing='wefwefe'
}

returnone() {
    return 1 
}


# echo 'running'

# other
# random arg asd sdf gd

# cd ~/Code/csv_checker
# read -p 'yes or no (y/n) ' ans
# ans=$(random)
# ans=''
# $ans <<< random
# echo $ans


