#!/bin/sh

# To ease my setup on new computers ugh

#Set up the rcs
if [ -f ~/.bashrc ]; then
    echo ".bashrc exists already"
    if grep -q "dotfiles/bashrc" ~/.bashrc; then
        echo -e "\tdotfiles/bashrc is already sourced in existing .bashrc"
    elif [ -L ~/.bashrc ]; then
        echo -e "\t~/.bashrc is a symlink. Let's leave that alone for now."
    else
        echo -e "\tAppending command to source dotfiles/bashrc to end of existing .bashrc..."
        echo "source ~/dotfiles/bashrc" >> ~/.bashrc
        echo -e "\tdone"
    fi
    echo -e "\t moving on..."
else
    echo ".bashrc does not exist... creating soft symlink to dotfiles/bashrc"
    ln -s ~/dotfiles/bashrc ~/.bashrc
fi

if [ -f ~/.inputrc ]; then
    echo ".inputrc exists already"
    if grep -q "dotfiles/inputrc" ~/.inputrc; then
        echo -e "\tdotfiles/inputrc is already sourced in existing .inputrc"
    elif [ -L ~/.inputrc ]; then
        echo -e "\t~/.inputrc is a symlink. Let's leave that alone for now."
    else
        echo -e "\tAppending command to source dotfiles/inputrc to end of existing .inputrc..."
        echo "source ~/dotfiles/inputrc" >> ~/.inputrc
        echo -e "\tdone"
    fi
    echo -e "\t moving on..."
else
    echo ".inputrc does not exist... creating soft symlink to dotfiles/inputrc"
    ln -s ~/dotfiles/inputrc ~/.inputrc
fi

if [ -f ~/.vimrc ]; then
    echo ".vimrc exists already"
    if grep -q "dotfiles/vimrc" ~/.vimrc; then
        echo "dotfiles/vimrc is already sourced in existing .vimrc"
    elif [ -L ~/.vimrc ]; then
        echo -e "\t~/.vimrc is a symlink. Let's leave that alone for now."
    else
        echo -e "\tAppending command to source dotfiles/vimrc to end of existing .vimrc..."
        echo ":so ~/dotfiles/vimrc" >> ~/.vimrc
        echo -e "\tdone"
    fi
    echo -e "\t moving on..."
else
    echo ".vimrc does not exist... creating soft symlink to dotfiles/vimrc"
    ln -s ~/dotfiles/vimrc ~/.vimrc
fi

#  TODO: 
# -  inputrc
# - install any packages I want.. maybe?
# - maybe make sure vim is up to date?

# Set up vim vundle plugin manager
if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim +PluginInstall +qall
else
    echo "Vundle already installed"
fi

=======
# -  check if symlink already before appending source whatever

# Set up vim vundle plugin manager
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Make sure vim is as updated as can be
# sudo apt-get update
# sudo apt-get install vim
